-- Seed demo data for Class AId prototype
-- This provides a working demo without requiring any setup

-- Demo users
INSERT OR IGNORE INTO users (id, name, email, role) VALUES
  ('user-learner-1', 'Alex Tan', 'alex.tan@university.edu', 'learner'),
  ('user-learner-2', 'Marcus Chen', 'marcus.chen@university.edu', 'learner'),
  ('user-learner-3', 'Priya Sharma', 'priya.sharma@university.edu', 'learner'),
  ('user-instructor-1', 'Dr Sarah Lim', 's.lim@university.edu', 'instructor'),
  ('user-admin-1', 'Daniel Wong', 'd.wong@university.edu', 'admin');

-- Domain
INSERT OR IGNORE INTO domains (id, name, description, compliance_label) VALUES
  ('domain-1', 'Electrical & Electronics Engineering', 'Measurement, circuits, instrumentation, and electrical safety', 'Laboratory Safety Compliance');

-- Module
INSERT OR IGNORE INTO modules (id, domain_id, title, description, owner_id, status, version, overall_threshold, estimated_minutes) VALUES
  ('module-1', 'domain-1', 'Digital Multimeter Fundamentals and Safety', 'Prepare for hands-on multimeter use by understanding measurement principles, correct connection procedures, safety requirements, and common error sources.', 'user-instructor-1', 'published', '1.2.0', 0.8, 25);

-- Competencies
INSERT OR IGNORE INTO competencies (id, module_id, name, description, weight, min_threshold, mandatory, critical, sequence) VALUES
  ('comp-1', 'module-1', 'Measurement Theory', 'Understanding of voltage, current, and resistance measurement principles', 0.25, 0.6, 1, 0, 1),
  ('comp-2', 'module-1', 'Connection Procedures', 'Correct probe placement and mode selection for each measurement type', 0.30, 0.7, 1, 0, 2),
  ('comp-3', 'module-1', 'Safety Compliance', 'Critical safety rules, PPE, and prohibited actions', 0.30, 0.8, 1, 1, 3),
  ('comp-4', 'module-1', 'Error Awareness', 'Common measurement errors and their prevention', 0.15, 0.5, 0, 0, 4);

-- Activities
INSERT OR IGNORE INTO activities (id, module_id, title, activity_type, sequence, content, explanation, warning, competency_id) VALUES
  ('act-1', 'module-1', 'Understanding Your Digital Multimeter', 'instruction', 1, 'A digital multimeter (DMM) measures voltage, current, and resistance. The display shows the measured value, while the rotary selector chooses the measurement function and range. Most modern DMMs have auto-ranging capability.', 'The DMM is the most common instrument in electronics laboratories. Understanding its functions before use prevents measurement errors and equipment damage.', NULL, 'comp-1'),
  ('act-2', 'module-1', 'Voltage Measurement — Parallel Connection', 'demonstration', 2, 'Voltage is always measured in PARALLEL with the component. Connect the red probe to the V/Ω terminal and the black probe to COM. Place probes across the component while the circuit is energised. The multimeter presents very high input impedance so it draws negligible current.', 'Parallel connection means the multimeter measures the potential difference across the component without significantly altering circuit behaviour.', NULL, 'comp-2'),
  ('act-3', 'module-1', 'Current Measurement — Series Connection', 'demonstration', 3, 'Current is measured in SERIES with the circuit. You must break the circuit and insert the multimeter so all current flows through it. Connect the red probe to the mA/A terminal (not the V/Ω terminal). Select the appropriate current range BEFORE connecting.', 'Series connection ensures all circuit current passes through the meter. Using the wrong terminal or connecting in parallel while in current mode can blow the internal fuse or damage the meter.', 'Never connect the multimeter in parallel when set to current measurement mode. This creates a short circuit.', 'comp-2'),
  ('act-4', 'module-1', 'Critical Safety Rules', 'warning', 4, 'CRITICAL RULES: 1. Never exceed the maximum input voltage rating (typically 600V CAT III or 1000V CAT II). 2. Always verify the measurement mode BEFORE connecting probes to a live circuit. 3. Never measure resistance in a live (energised) circuit. 4. Use appropriate PPE (safety glasses, insulated gloves for >50V). 5. Inspect probe insulation before every use — do not use damaged probes.', 'These rules are non-negotiable. Violation can cause equipment damage, electric shock, arc flash, or fire. A failure to demonstrate understanding of any critical rule prevents a Ready status.', 'Failure to follow these rules can result in serious injury or death. These are mandatory requirements.', 'comp-3'),
  ('act-5', 'module-1', 'Resistance Measurement Procedure', 'instruction', 5, 'To measure resistance: 1) De-energise the circuit completely. 2) Disconnect the component if possible. 3) Select resistance mode (Ω). 4) Connect probes across the component. 5) Read the value. The meter applies a small test voltage — if the circuit is live, the reading will be incorrect and the meter may be damaged.', 'Resistance measurement requires a de-energised circuit because the DMM injects its own test signal. External voltage interferes with this signal and can damage the meter.', 'Always ensure the circuit is completely de-energised before measuring resistance.', 'comp-2'),
  ('act-6', 'module-1', 'Common Measurement Errors', 'practice', 6, 'Common errors to recognise: Probes in wrong terminals (V terminal when measuring current), Wrong mode selected (AC vs DC), Measuring resistance in a live circuit, Not zeroing the meter before low-resistance measurement, Loose probe connections giving unstable readings, Exceeding the range (reading shows "OL" or "1.")', 'Recognising these error patterns helps you troubleshoot unexpected readings before assuming the circuit has a fault.', NULL, 'comp-4'),
  ('act-7', 'module-1', 'Pre-Lab Checklist Review', 'reflection', 7, 'Before entering the laboratory, confirm you can answer: How do I connect probes for voltage vs current measurement? What mode and terminal do I use for each measurement? What must I check before measuring resistance? What are the critical safety rules I must never violate? How do I recognise a measurement error?', 'This checklist mirrors what your readiness assessment will evaluate. If you cannot answer these confidently, review the relevant steps above.', NULL, 'comp-1');

-- Assessment Questions (5 questions, 2 critical)
INSERT OR IGNORE INTO questions (id, module_id, competency_id, question_text, question_type, options, correct_answer, explanation, critical, source_reference, question_kind, approval_status) VALUES
  ('q-1', 'module-1', 'comp-1', 'Why must voltage be measured in parallel with a component rather than in series?', 'multiple-choice', '["Because the multimeter needs high current to measure voltage","Because parallel connection allows the meter to measure potential difference without significantly altering circuit current","Because series connection would give a higher voltage reading","Because the multimeter cannot physically be connected in series"]', 'Because parallel connection allows the meter to measure potential difference without significantly altering circuit current', 'A voltmeter has very high input impedance and is connected in parallel to measure the potential difference across a component without drawing significant current from the circuit.', 0, 'DMM Manual v3.1, Section 2.1 — Voltage Measurement Principles', 'assessment', 'approved'),
  ('q-2', 'module-1', 'comp-2', 'When measuring current, which terminal should the red probe be connected to?', 'multiple-choice', '["The V/Ω terminal","The COM terminal","The mA/A terminal","Any terminal — it does not matter for current measurement"]', 'The mA/A terminal', 'For current measurement, the red probe must be in the mA or A terminal (depending on expected range). Using the V/Ω terminal while in current mode creates a short circuit path.', 0, 'DMM Manual v3.1, Section 3.2 — Current Measurement Connections', 'assessment', 'approved'),
  ('q-3', 'module-1', 'comp-3', 'What must you verify BEFORE connecting multimeter probes to a live circuit?', 'multiple-choice', '["That the battery is fully charged","That the measurement mode and range are correctly set for the intended measurement","That the display backlight is working","That the auto-range feature is enabled"]', 'That the measurement mode and range are correctly set for the intended measurement', 'Connecting probes with the wrong mode selected can create dangerous short circuits, blow fuses, or damage equipment. Always verify mode BEFORE connecting to a live circuit.', 1, 'DMM Manual v3.1, Section 5.1 — Critical Safety Procedures', 'assessment', 'approved'),
  ('q-4', 'module-1', 'comp-3', 'Why is it dangerous to measure resistance in a live (energised) circuit?', 'multiple-choice', '["It gives slightly inaccurate readings","The display may flicker","The external voltage can damage the meter, give false readings, and create a safety hazard","It only matters for resistance values above 1MΩ"]', 'The external voltage can damage the meter, give false readings, and create a safety hazard', 'The DMM injects a small test voltage for resistance measurement. External circuit voltage overwhelms this signal, causing incorrect readings, potential meter damage, and possible shock or arc hazard.', 1, 'DMM Manual v3.1, Section 5.3 — Resistance Measurement Safety', 'assessment', 'approved'),
  ('q-5', 'module-1', 'comp-4', 'You see "OL" on the multimeter display while measuring resistance. What does this most likely indicate?', 'multiple-choice', '["The battery is low","The circuit is open (infinite resistance) or the component value exceeds the selected range","The probes are connected correctly","The measurement is complete and should be recorded as zero"]', 'The circuit is open (infinite resistance) or the component value exceeds the selected range', '"OL" (overload) means the resistance is beyond the meter''s ability to measure in the current range. This typically means an open circuit, a disconnected component, or a need to select a higher range.', 0, 'DMM Manual v3.1, Section 6.2 — Interpreting Display Indicators', 'assessment', 'approved');

-- Checkpoint questions (approved)
INSERT OR IGNORE INTO questions (id, module_id, competency_id, question_text, question_type, options, correct_answer, explanation, critical, question_kind, activity_id, approval_status, failure_hint, min_read_seconds, generated_at, approved_by, approved_at) VALUES
  ('cp-1', 'module-1', 'comp-1', 'What does the rotary selector on a digital multimeter control?', 'multiple-choice', '["The brightness of the display","The measurement function and range","The battery level indicator","The probe connection type"]', 'The measurement function and range', 'The rotary selector chooses which measurement function and range the multimeter uses.', 0, 'checkpoint', 'act-1', 'approved', 'Re-read the first paragraph about the rotary selector and its purpose.', 20, '2026-07-25T09:00:00Z', 'user-instructor-1', '2026-07-26T10:00:00Z'),
  ('cp-2', 'module-1', 'comp-2', 'How must a voltmeter be connected to measure the potential difference across a component?', 'multiple-choice', '["In series with the component","In parallel with the component","Disconnected from the circuit","Connected to ground only"]', 'In parallel with the component', 'Voltage is always measured in parallel.', 0, 'checkpoint', 'act-2', 'approved', 'Review the key principle: voltage = parallel connection.', 25, '2026-07-25T09:00:00Z', 'user-instructor-1', '2026-07-26T10:05:00Z'),
  ('cp-3', 'module-1', 'comp-2', 'What must you do to the circuit before inserting the multimeter for current measurement?', 'multiple-choice', '["Increase the voltage","Break the circuit so current flows through the meter","Add a parallel resistor","Nothing — just touch the probes to any point"]', 'Break the circuit so current flows through the meter', 'Current measurement requires series insertion.', 0, 'checkpoint', 'act-3', 'approved', 'Focus on the word SERIES. The circuit must be broken.', 30, '2026-07-25T09:00:00Z', 'user-instructor-1', '2026-07-26T10:10:00Z'),
  ('cp-4', 'module-1', 'comp-3', 'What is the consequence of failing to verify the measurement mode BEFORE connecting probes to a live circuit?', 'multiple-choice', '["The display shows a slightly wrong number","The backlight turns off","It can create dangerous short circuits, blow fuses, or damage equipment","The auto-range takes longer to settle"]', 'It can create dangerous short circuits, blow fuses, or damage equipment', 'Wrong mode + live circuit = potential short circuit.', 1, 'checkpoint', 'act-4', 'approved', 'THIS IS A CRITICAL SAFETY RULE. Re-read all 5 critical rules carefully.', 45, '2026-07-25T09:00:00Z', 'user-instructor-1', '2026-07-26T10:15:00Z'),
  ('cp-5', 'module-1', 'comp-2', 'What is the FIRST step before measuring resistance?', 'multiple-choice', '["Select the highest range","Connect the red probe to the mA terminal","De-energise the circuit completely","Zero the display"]', 'De-energise the circuit completely', 'Resistance measurement requires a dead circuit.', 0, 'checkpoint', 'act-5', 'approved', 'Look at step 1 of the resistance procedure.', 25, '2026-07-25T09:00:00Z', 'user-instructor-1', '2026-07-26T10:20:00Z'),
  ('cp-6', 'module-1', 'comp-4', 'If you see "OL" on the display while measuring resistance, what should you suspect?', 'multiple-choice', '["The battery needs replacing","The circuit is open or the value exceeds the selected range","The measurement is complete and correct","The probes are correctly connected"]', 'The circuit is open or the value exceeds the selected range', '"OL" means overload.', 0, 'checkpoint', 'act-6', 'approved', 'Look at the error patterns list. Find "OL".', 30, '2026-07-25T09:00:00Z', 'user-instructor-1', '2026-07-26T10:25:00Z'),
  ('cp-7', 'module-1', 'comp-1', 'Before entering the laboratory, which of the following should you be able to answer confidently?', 'multiple-choice', '["The price of the multimeter model","How to connect probes for voltage vs current, safety rules, and how to recognise errors","The manufacturer warranty terms","How to calibrate the meter"]', 'How to connect probes for voltage vs current, safety rules, and how to recognise errors', 'The pre-lab checklist covers connections, modes, prerequisites, safety, and errors.', 0, 'checkpoint', 'act-7', 'approved', 'Review the 5 checklist questions.', 20, '2026-07-25T09:00:00Z', 'user-instructor-1', '2026-07-26T10:30:00Z');

-- Initial audit events
INSERT OR IGNORE INTO audit_events (id, actor_id, actor_name, action, entity_type, entity_id, details) VALUES
  ('audit-1', 'user-instructor-1', 'Dr Sarah Lim', 'MODULE_PUBLISHED', 'module', 'module-1', 'Published version 1.2.0 of Digital Multimeter Fundamentals and Safety'),
  ('audit-2', 'user-instructor-1', 'Dr Sarah Lim', 'QUESTIONS_APPROVED', 'question', 'module-1', 'Approved 5 assessment questions including 2 critical safety questions'),
  ('audit-3', 'user-admin-1', 'Daniel Wong', 'SOURCE_UPDATED', 'source', 'module-1', 'Updated source material to DMM-Manual-v3.1'),
  ('audit-4', 'user-instructor-1', 'Dr Sarah Lim', 'CHECKPOINTS_APPROVED', 'question', 'module-1', 'Approved 7 comprehension checkpoint questions for adaptive learning');
