import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';

/**
 * Class AId AWS Production Stack
 *
 * This stack defines the target AWS infrastructure for Class AId,
 * replacing the current free-tier Cloudflare + Supabase + Groq stack.
 *
 * Current architecture:
 *   Browser -> Cloudflare Pages (static + functions)
 *     -> Supabase (PostgreSQL + pgvector + Auth + Storage)
 *     -> Groq (Llama 3.1 70B)
 *     -> Cloudflare Workers AI (BGE-base-en-v1.5 embeddings)
 *
 * Target architecture:
 *   Browser -> CloudFront -> S3 (static)
 *   Browser -> CloudFront -> API Gateway -> Lambda (API)
 *     -> Aurora Serverless v2 (PostgreSQL + pgvector)
 *     -> Amazon Bedrock (Claude 3.5 Sonnet for generation)
 *     -> Amazon Bedrock (Titan Embeddings)
 *     -> Cognito (Auth)
 *     -> S3 (File Storage)
 */
export class ClassAidStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // =========================================================================
    // VPC
    // =========================================================================
    // Provides network isolation for Aurora and Lambda.
    // Not needed in current stack (Supabase is fully managed SaaS).
    //
    // const vpc = new cdk.aws_ec2.Vpc(this, 'ClassAidVpc', {
    //   maxAzs: 2,
    //   natGateways: 1, // Minimize cost; Lambda needs NAT for Bedrock access
    // });

    // =========================================================================
    // Aurora Serverless v2 (PostgreSQL + pgvector)
    // Replaces: Supabase PostgreSQL + pgvector
    // =========================================================================
    // Aurora Serverless v2 scales capacity automatically based on load.
    // The pgvector extension provides vector similarity search for RAG.
    // Minimum 0.5 ACU keeps costs low during idle periods.
    //
    // const dbCluster = new cdk.aws_rds.DatabaseCluster(this, 'ClassAidDb', {
    //   engine: cdk.aws_rds.DatabaseClusterEngine.auroraPostgres({
    //     version: cdk.aws_rds.AuroraPostgresEngineVersion.VER_15_4,
    //   }),
    //   serverlessV2MinCapacity: 0.5,
    //   serverlessV2MaxCapacity: 4,
    //   writer: cdk.aws_rds.ClusterInstance.serverlessV2('writer'),
    //   vpc,
    //   vpcSubnets: { subnetType: cdk.aws_ec2.SubnetType.PRIVATE_WITH_EGRESS },
    //   defaultDatabaseName: 'classaid',
    //   credentials: cdk.aws_rds.Credentials.fromGeneratedSecret('classaid_admin'),
    // });

    // =========================================================================
    // S3 Bucket - Static Site Hosting
    // Replaces: Cloudflare Pages (static hosting)
    // =========================================================================
    // Hosts the Next.js static export (out/ directory).
    // CloudFront serves as the CDN in front of S3.
    //
    // const siteBucket = new cdk.aws_s3.Bucket(this, 'SiteBucket', {
    //   bucketName: `classaid-site-${this.account}`,
    //   blockPublicAccess: cdk.aws_s3.BlockPublicAccess.BLOCK_ALL,
    //   encryption: cdk.aws_s3.BucketEncryption.S3_MANAGED,
    //   removalPolicy: cdk.RemovalPolicy.RETAIN,
    // });

    // =========================================================================
    // S3 Bucket - File Storage
    // Replaces: Supabase Storage (source-files bucket)
    // =========================================================================
    // Stores uploaded source documents for processing.
    // Access controlled via pre-signed URLs generated by Lambda.
    //
    // const filesBucket = new cdk.aws_s3.Bucket(this, 'FilesBucket', {
    //   bucketName: `classaid-files-${this.account}`,
    //   blockPublicAccess: cdk.aws_s3.BlockPublicAccess.BLOCK_ALL,
    //   encryption: cdk.aws_s3.BucketEncryption.S3_MANAGED,
    //   lifecycleRules: [
    //     { expiration: cdk.Duration.days(365) }, // Auto-cleanup after 1 year
    //   ],
    // });

    // =========================================================================
    // CloudFront Distribution
    // Replaces: Cloudflare Pages CDN + Workers routing
    // =========================================================================
    // Serves static site from S3 and routes /api/* to API Gateway.
    // Provides edge caching, HTTPS termination, and custom domain support.
    //
    // const distribution = new cdk.aws_cloudfront.Distribution(this, 'Distribution', {
    //   defaultBehavior: {
    //     origin: new cdk.aws_cloudfront_origins.S3Origin(siteBucket),
    //     viewerProtocolPolicy: cdk.aws_cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
    //   },
    //   additionalBehaviors: {
    //     '/api/*': {
    //       origin: new cdk.aws_cloudfront_origins.HttpOrigin('API_GATEWAY_DOMAIN'),
    //       viewerProtocolPolicy: cdk.aws_cloudfront.ViewerProtocolPolicy.HTTPS_ONLY,
    //       allowedMethods: cdk.aws_cloudfront.AllowedMethods.ALLOW_ALL,
    //       cachePolicy: cdk.aws_cloudfront.CachePolicy.CACHING_DISABLED,
    //     },
    //   },
    //   defaultRootObject: 'index.html',
    //   errorResponses: [
    //     { httpStatus: 404, responsePagePath: '/index.html', responseHttpStatus: 200 },
    //   ],
    // });

    // =========================================================================
    // Lambda Functions
    // Replaces: Cloudflare Pages Functions (functions/api/*)
    // =========================================================================
    // Each Pages Function maps to a Lambda handler.
    // The core business logic (validation, scoring) remains identical.
    // Only the runtime adapter (event shape) changes.
    //
    // Lambda functions:
    //   - api-modules: GET /api/modules (list/get modules)
    //   - api-assessments: POST /api/assessments (submit/score)
    //   - api-chat: POST /api/chat (AI coach)
    //   - api-upload: POST /api/upload (file upload + chunking)
    //   - api-generate: POST /api/generate (question generation)
    //   - api-checkpoints: POST /api/checkpoints (checkpoint progress)
    //   - api-insights: GET /api/insights (instructor analytics)
    //
    // const apiFunction = new cdk.aws_lambda.Function(this, 'ApiFunction', {
    //   runtime: cdk.aws_lambda.Runtime.NODEJS_22_X,
    //   handler: 'index.handler',
    //   code: cdk.aws_lambda.Code.fromAsset('../../../functions-dist'),
    //   environment: {
    //     DATABASE_SECRET_ARN: 'from-secrets-manager',
    //     BEDROCK_MODEL_ID: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
    //     BEDROCK_EMBEDDING_MODEL_ID: 'amazon.titan-embed-text-v2:0',
    //   },
    //   timeout: cdk.Duration.seconds(30),
    //   memorySize: 512,
    //   vpc,
    //   vpcSubnets: { subnetType: cdk.aws_ec2.SubnetType.PRIVATE_WITH_EGRESS },
    // });

    // =========================================================================
    // API Gateway
    // Replaces: Cloudflare Pages Functions routing
    // =========================================================================
    // REST API with Lambda proxy integration.
    // Cognito authorizer protects authenticated endpoints.
    //
    // const api = new cdk.aws_apigateway.RestApi(this, 'ClassAidApi', {
    //   restApiName: 'ClassAid API',
    //   description: 'Class AId API Gateway',
    //   defaultCorsPreflightOptions: {
    //     allowOrigins: cdk.aws_apigateway.Cors.ALL_ORIGINS,
    //     allowMethods: cdk.aws_apigateway.Cors.ALL_METHODS,
    //   },
    // });

    // =========================================================================
    // Cognito User Pool
    // Replaces: Supabase Auth
    // =========================================================================
    // Handles user registration, login, and JWT token issuance.
    // Integrates with API Gateway for request authorization.
    // Supports email/password authentication (matching Supabase Auth config).
    //
    // const userPool = new cdk.aws_cognito.UserPool(this, 'UserPool', {
    //   userPoolName: 'classaid-users',
    //   selfSignUpEnabled: true,
    //   signInAliases: { email: true },
    //   autoVerify: { email: true },
    //   standardAttributes: {
    //     email: { required: true, mutable: false },
    //     fullname: { required: true, mutable: true },
    //   },
    //   passwordPolicy: {
    //     minLength: 8,
    //     requireLowercase: true,
    //     requireUppercase: true,
    //     requireDigits: true,
    //     requireSymbols: false,
    //   },
    //   accountRecovery: cdk.aws_cognito.AccountRecovery.EMAIL_ONLY,
    //   removalPolicy: cdk.RemovalPolicy.RETAIN,
    // });
    //
    // const userPoolClient = new cdk.aws_cognito.UserPoolClient(this, 'UserPoolClient', {
    //   userPool,
    //   authFlows: {
    //     userPassword: true,
    //     userSrp: true,
    //   },
    // });

    // =========================================================================
    // Secrets Manager
    // Replaces: Cloudflare Pages environment variables (encrypted)
    // =========================================================================
    // Stores sensitive configuration that Lambda functions retrieve at runtime.
    // Supports automatic rotation for database credentials.
    //
    // const apiSecrets = new cdk.aws_secretsmanager.Secret(this, 'ApiSecrets', {
    //   secretName: 'classaid/api-keys',
    //   description: 'Class AId API keys and secrets',
    //   generateSecretString: {
    //     secretStringTemplate: JSON.stringify({
    //       BEDROCK_REGION: 'eu-west-1',
    //     }),
    //     generateStringKey: 'placeholder',
    //   },
    // });

    // =========================================================================
    // Stack Outputs
    // =========================================================================
    // Useful values for deployment scripts and documentation.
    //
    // new cdk.CfnOutput(this, 'CloudFrontUrl', {
    //   value: distribution.distributionDomainName,
    //   description: 'CloudFront distribution URL',
    // });
    //
    // new cdk.CfnOutput(this, 'ApiUrl', {
    //   value: api.url,
    //   description: 'API Gateway URL',
    // });
    //
    // new cdk.CfnOutput(this, 'UserPoolId', {
    //   value: userPool.userPoolId,
    //   description: 'Cognito User Pool ID',
    // });
    //
    // new cdk.CfnOutput(this, 'UserPoolClientId', {
    //   value: userPoolClient.userPoolClientId,
    //   description: 'Cognito User Pool Client ID',
    // });
  }
}
